encoding/resp/resp.go
If the return value is less than 0 ，lead to panic
=> fix resp package BulkString funtion

metrics/prometheus.go
=> register sdk metrics

command/connection.go
Add the missing `return` statement
=> Fix: missing return

db/hash.go, db/hash_test.go
GetHash does not use the meta in the store to determine whether it expires
=> hash check expire time fail

.gitignore, .travis.yml
- Add gitignore to untrack unused files (make your `git status` clean);
- Add `go_import_path` in travis CI script to make sure successful building when you fork project to your own repo;
=> Add gitignore and refine travis CI script

command/server.go, db/db.go, db/kv.go, db/util.go, go.mod
=> FlushDB and FlushAll failed

db/store/store.go, go.mod
Update TiKV SDK to the v2.1.5 
replace BatchGetValues to BatchGet
=> update Tikv sdk to 2.1.5

titan.go
=> remove unreachable code

proposals/zset.md
=> zset的设计proposal

command/command.go, command/hashes.go, command/hashes_test.go, command/init.go, command/keys.go, command/server.go, command/transactions.go, db/codec.go, db/db.go, db/hash.go, db/hash_test.go, db/kv.go, metrics/prometheus.go
Delete the Len field and MateSloat in the hash-meta
=> Feature/Delete the Len field and MateSloat in the hash-meta

command/sets.go
Remove the maxheap and use minheap only.
=> Refactor sunion/sinter by minheap

bin/titan/main.go
=> fix:server tls panic

client.go
Signed-off-by: lugang <lugang@zhuanzhuan.com>
=> Log EOF to info level

docker-compose.yml
Export titan logs from docker-compose
=> fix(docker-compose): export titan logs

command/zsets.go, tools/autotest/abnormal.go
change zadd error output to follow redis
=> change zadd error output to follow redis

.travis.yml, Makefile, command/hashes.go, command/hashes_test.go
https://github.com/golangci/golangci-lint
for more information
=> Feature: add ci linter

db/gc_test.go
Fixed a problem in gc test where dirty data could not pass through the test
=> fix gc test err

db/codec.go, db/codec_test.go, db/db.go, db/expire.go, db/gc.go, db/gc_test.go, db/hash.go, db/list.go, db/llist.go, db/object.go, db/set.go, db/string.go, db/tikvgc.go, db/zlist.go, db/zset.go, db/ztransfer.go
Fix db package error related to golangci-lint tool
=> feat(db package): it satisfies the test result of golangci-lint tool

conf/config.go, conf/titan.toml, db/db.go, db/db_test.go
Remove the configuration of hash slot
Closes: #133
=> fix(config): remove hash slot

proposals/README.md
=> docs: add the proposal guidelines

bin/titan/main.go, command/test_test.go, conf/config.go, conf/mockconfig.go, db/db.go, db/db_test.go, db/expire.go, db/expire_test.go, db/gc.go, db/gc_test.go, db/kv.go, db/test_test.go, db/tikvgc.go, metrics/prometheus.go, proposals/set-design-en.md, tools/integration/titan.go
=> refactor: rename Tikv to TiKV

.gitignore, docs/command_list.md
=> update doc according we have already supported reverse operations

command/init.go, command/keys.go, db/kv.go, docs/command_list.md, go.mod
=> command: implement touch command

db/expire.go, db/gc.go, db/store/store.go
=> feat(gc): txn use low priority

Dockerfile
=> update docker image builder version to support go mod

conf/titan.toml
=> feat(conf): update titan conf

db/kv.go
It is not random in fact, it is difficult to return a key in a really
random way. We use a two-step random strategy here to return a key, but
its distribution is not uniform. The main propose of this command is to
return a key to inspect the database, so the random guarantee is not
always necessary.
=> command: improve the randomkey command

bin/titan/main.go, conf/config.go, conf/titan.toml
Put TiKVLogger into TiKV
Closes: #164
=> feat(conf):move TikvLog to TiKV

client.go
=> panic when cmd is nil

docs/metrics/Titan-Server-1581907442715.json, docs/metrics/titan-grafana-dashboard.json
=> feat(add metrics):

docker-compose.yml, docs/metrics/monitoring configuration instructions.md, docs/metrics/titan-grafana-dashboard.json
-  Add monitoring instructions
- Update the monitor profile and delete the group field
- Add the monitoring port in docker-compose
=> feat: add metrics instructions

db/llist.go
fix RPOP bug [199](https://github.com/distributedio/titan/issues/199)
=> fix: RPOP bug

command/command.go
BytesArray repeat writing to the closed connection
=> fix: repeat writing to the closed connection

db/db.go, docs/command_list.md
if disable ExternalConsistency,Async commit does not ensure linearizability
https://github.com/tikv/tikv/issues/8589
https://asktug.com/t/topic/68491/4
=> enable ExternalConsistency

db/expire.go, db/gc.go, db/task.go, db/tikvgc.go, db/ztransfer.go
=> Fix the election

db/db.go
Fix https://github.com/distributedio/titan/issues/219
=> Fix: omit backgroud task when working on a mock tikv
