command/server_test.go

The lengh of a timestamp is not fixed, so the unitest may fail
before.

Fix unittest for monitor

---

db/codec.go
db/codec_test.go

This PR fixed the bug of EncodeInt64 that could not guarantee memcomparable

Fix encoding bug of int64

---

client.go

Use the `rootContext` on each command execution to avoid the bugs of TiKV SDK.
There is a bug in TiKV SDK, the SDK commits the secondary batch of keys in the background with the context that the client supplied, when the context is canceled, the job will be aborted and then causes some secondary locks left on keys which should have been cleaned up.

Remove cancel on each command

---

go.mod

Update TiKV SDK to the laster master to avoid memory leaks. Details: https://github.com/pingcap/tidb/pull/9121

Update tidb to the latest master

---

go.mod

env GO111MODULE=on go get github.com/pingcap/tidb@release-2.1

Backoff TiKV SDK to release-2.1

---

command/test_test.go
conf/config.go
conf/mockconfig.go
conf/titan.toml
db/db.go
db/db_test.go
db/expire.go
db/gc.go
db/test_test.go
db/tikvgc.go
db/ztransfer.go
tools/integration/titan.go

Move the gc/expire related configuration to the titan.toml configuration file

 move interval to config file from gc/expire work

---

db/hash.go
db/hash_test.go

Old hash keys do not work when changing the titan.toml file meta-slot configuration item

fixed meta-slot  configuration item cannot be activated

---

go.mod

删除`go.mod`中对`github.com/meitu/titan` 的依赖

删除go.mod中对github.com/meitu/titan 的依赖

---

bin/titan/main.go
go.mod

Transfer shafreeck/continuous to distributeio/continuous to keep more healthy of the project.
Closes https://github.com/distributedio/titan/issues/103

transfer continuous to distributedio

---

db/db.go

Record the debug log when decode errors occur in the db.strings method

fix:db.strings error log 

---

conf/config.go
conf/mockconfig.go
conf/titan.toml
db/expire.go
db/gc.go
db/tikvgc.go
db/ztransfer.go

Some of the configo issues make the enable configuration items unavailable with a default value of false. Rename enable to disable and change the default value to true

fix:replace enable conf to disable

---

tools/expire/main.go

When the expire feature has a bug, it may cause dirty keys that expected to be expired. This is a tool to scan the whole database, reading its meta and clean it up if it has expired.

tool: expire is a tool to scan the whole database to expire keys

---

client.go
command/transactions.go

fixes #126
When a transaction is executed with failure, the pending commands are not cleared.  If this client sends the next transaction, the last commands will be executed and replied.
PS: A transaction is a series of commands: `watch ... multi ... exec`

Cleanup the pending commands of a client when the txn is executed

---

Dockerfile

`scratch` image is too empty to debug, use `alpine` which contains some basic commands.

dockerfile: use alpine instead of scratch

---

README.md
command/init.go
docs/command_list.md

Closes #105
unlink is the same as del in design, both purging the data in the
backgroud by GC for large object.

command: implement unlink command

---

command/command.go
command/zsets.go
encoding/resp/resp.go

Closes #165 
Do not maintain two different functions that implementing the same feature. Improve the performance of `BytesArray` if necessary.

feat(resp): use BytesArray instead of BytesArrayOnce

---

command/extension.go
command/init.go
db/expire.go
db/expire_test.go

Closes #46
Implement an extension command `escan` which scans the expiration list.
Usage:
```
escan [from ts] [to ts] [count N]
> escan
> escan count 10
> escan from 0 count 10
> escan from 0 to 1578660490175858196 count 20
```

command: implement the extension command: escan

---

bin/titan/main.go
conf/config.go
conf/titan.toml
go.mod

It is inconvenient to deploy the whole TiKV cluster to try Titan, fortunately, we can use the `mocktikv` as a backend. This PR configures the titan.toml to use `mocktikv://` as the default address.

config: use mocktikv:// as the default pd address

---

command/connection.go

根据redis源码[pong](https://github.com/antirez/redis/blob/3.2/src/server.c#L1384)，返回PONG时使用的是simple string，而不是bulk string

返回PONG时应该使用Simple String

---

command/init.go

Add getset command in commands initialization

---

db/llist.go

LListMeta 序列化需要的字节数组长度是24(3*8)

fix: LListMeta marshal bytes array length
